name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    # Only deploy if tests pass

    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST "${{ secrets.MY_DEP }}"

